### ISSUE TITLE
Type error with the generated .d.ts file, but only when its installed in node_modules?

### ISSUE THREAD

**Issue by Sammons** [serafin-labs/schema-builder#1]
![screenshot from 2019-02-24 21-12-05](https://user-images.githubusercontent.com/1619603/53310030-1a99dc00-3879-11e9-9080-79b1ce4f2ef6.png)

**Comment by Sammons** [comment]
Ah, I can close this. Its only when strict=true in the tsconfig

**Comment by sebastien-de-saint-florent** [comment]
Indeed strict mode is not activated. But it could be nice to have it! Thanks for the report 👍

**Comment by simonhull** [comment]
Can I ask what the motivation is for not allowing strict?  We're trying to use this in an application and this issue is preventing us from using this package.

**Comment by sebastien-de-saint-florent** [comment]
@simonhull 
I'm glad you want to try out this lib! (Despite its lonely five stars and 0.x version number)

It actually wasn't made on purpose. We created this repo without strict mode enabled and we never took the time to fix issues related to it.
We are still beta testing this library on our own startup project and I have very little bandwidth to fix this kind of thing. I will have a look into it this week to see if it's possible. I'll keep you posted on this thread.

In the meantime, I'm interested in knowing more about your use case and/or having feedback from you about this lib

Thanks

**Comment by mordof** [comment]
@sebastien-de-saint-florent 
I'm working with @simonhull . We have a number of uses for this library that would really make our lives easier. 

In our node (typescript) API services, we use JSON schema to validate the body being supplied to an endpoint - an added benefit here would be the ability to type the body of the request using the generated `SchemaBuilder.T`. It's also a lot nicer writing json schema with your schema builder than it is writing plain json schema.

In our ORM database models, we're looking to use json schema for validating the data at run time. Again, from a Typescript perspective, we could then also use the generated Types for our models too, to a certain degree (being able to manipulate the schema builder as-needed is useful for that for variations as well).

We're also looking at using the JSON schema which validates our endpoint body to supply our front-end code with types of what the API is expecting too.

As for any feedback, we haven't had much actual use yet, as all our code is in strict mode (initial attempts with build failure stopped us in our tracks pretty quick). We did happen to get a similar error, but on a different location, than the original post though:

```
node_modules/@serafin/schema-builder/lib/SchemaBuilder.d.ts(145,70): error TS2344: Type 'null' does not satisfy the constraint 'keyof T'.
```

If there's anything further I can do to help, let me know. I'm interested in this seeing a proper resolution; If you have any pointers on how this might be addressed I can look into making a PR as well. Currently I'm a bit confused by my build error - it leads me to wonder if the issue is more complex than some simple fixes, but I can't be sure.

**Comment by sebastien-de-saint-florent** [comment]
@mordof 
Thanks for the feedback. I had already started working on it.
This was trickier than expected! Especially dealing with 'null' and index type transformations. It should be good now. Try the 0.7.0 and let me know if you still have issues.

**Comment by simonhull** [comment]
@sebastien-de-saint-florent Thanks for your help with this, our code is building successfully now!

**Comment by Sammons** [comment]
@simonhull I noticed your comment about extracting types; I have a project around extracting types from postgres https://github.com/sammons/morbid which isn't really finished but supports some basic CRUD and maybe could be re-purposed to help with that.
